@WebApi_HostAddress = https://localhost:7212/api

post {{WebApi_HostAddress}}/Auth/login
Accept: application/json
Content-type: application/json
{
  "email":"jobseeker@gmail.com",
  "password":"Jobseeker@12345678"
}
###
