// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Admin
{
    public long AdminId { get; set; }

    public long UserId { get; set; }

    public virtual User User { get; set; }
}