// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class RefreshToken
{
    public int Id { get; }

    public string Token { get; set; }

    public long? UserId { get; set; }

    public DateTime? Expires { get; set; }

    public bool IsRevoked { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedByIp { get; set; }

    public virtual User User { get; set; }
}