# For more info on HTTP files go to https://aka.ms/vs/httpfile
# "email":"user@gmail.com",
# "password":"User@12345678"
# "email":"jobseeker@gmail.com",
# "password":"Jobseeker@12345678"
# post {{WebApi_HostAddress}}/jobneeds/login
# Accept: application/json
# Content-type: application/json
# {
#  "email":"employer@gmail.com",
#  "password":"Employer@12345678"
# }
# 

@WebApi_HostAddress = https://localhost:7000

post {{WebApi_HostAddress}}/jobneeds/RegisterUser
Accept: application/json
Content-type: application/json
{
  "firstName":"sudhakar",
  "lastName":"garikipati",
  "email":"sudhakar@gmail.com",
  "phoneNumber":"+12142879851",
  "password":"Sudhakar@1234",
  "role":"Admin"
}
