// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobsModule.Domain.Entities;

public partial class EmployerJob
{
    public long EmployerJobId { get; set; }

    public long EmployerId { get; set; }

    public long JobId { get; set; }

    public virtual Employer Employer { get; set; }

    public virtual Job Job { get; set; }
}