// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobsModule.Domain.Entities;

public partial class Employer
{
    public long EmployerId { get; set; }

    public string CompanyName { get; set; }

    public string ContactPerson { get; set; }

    public string ContactEmail { get; set; }

    public string ContactPhone { get; set; }

    public string CompanyWebsite { get; set; }

    public string CompanyLocation { get; set; }

    public int? CompanySize { get; set; }

    public string Industry { get; set; }

    public string CompanyLogo { get; set; }

    public virtual ICollection<EmployerJob> EmployerJobs { get; set; } = new List<EmployerJob>();

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();
}