// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobsModule.Domain.Entities;

public partial class Job
{
    public long JobId { get; set; }

    public long EmployerId { get; set; }

    public string JobTitle { get; set; }

    public string JobDescription { get; set; }

    public string Location { get; set; }

    public string JobType { get; set; }

    public int? MinExperience { get; set; }

    public int? MaxExperience { get; set; }

    public int? MinSalary { get; set; }

    public int? MaxSalary { get; set; }

    public string Currency { get; set; }

    public string Skills { get; set; }

    public DateTime? PostedDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string Status { get; set; }

    public bool IsActive { get; set; }

    public string Url { get; set; }

    public virtual Employer Employer { get; set; }

    public virtual ICollection<EmployerJob> EmployerJobs { get; set; } = new List<EmployerJob>();

    public virtual ICollection<JobApplication> JobApplications { get; set; } = new List<JobApplication>();
}