// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobsModule.Domain.Entities;

public partial class JobApplication
{
    public long ApplicationId { get; set; }

    public long JobId { get; set; }

    public long UserId { get; set; }

    public DateTime? ApplicationDate { get; set; }

    public int Status { get; set; }

    public virtual Job Job { get; set; }

    public virtual User User { get; set; }
}