// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobsModule.Domain.Entities;

public partial class Subscription
{
    public int SubscriptionId { get; set; }

    public long EmployerId { get; set; }

    public int PlanId { get; set; }

    public int JobsQuota { get; set; }

    public DateTime ExpiryDate { get; set; }

    public DateTime CreatedDate { get; set; }
}