@JobsModule.API_HostAddress = https://localhost:7014/api

Post {{JobsModule.API_HostAddress}}/job/GetJobs
Accept: application/json
Content-type: application/json
{
  "title":"",
  "location":"Pune",
  "page":1,
  "pageSize": 10
}

###
